CREATE TABLE "assets" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"sticker_id" text,
	"kind" text NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"r2_key" text NOT NULL,
	"mime_type" text NOT NULL,
	"byte_size" integer,
	"width" integer,
	"height" integer,
	"frame_count" integer,
	"duration_seconds" double precision,
	"fps" double precision,
	"sha256" text,
	"has_alpha" boolean,
	"original_filename" text,
	"created_at" timestamp with time zone NOT NULL,
	"ready_at" timestamp with time zone,
	"sequence_columns" integer,
	"sequence_rows" integer,
	CONSTRAINT "assets_r2_key_unique" UNIQUE("r2_key"),
	CONSTRAINT "assets_kind_check" CHECK ("assets"."kind" IN ('reference', 'mask', 'master', 'preview', 'apng', 'gif', 'mp4', 'system', 'chat_attachment', 'sequence', 'attachment', 'video')),
	CONSTRAINT "assets_state_check" CHECK ("assets"."state" IN ('pending', 'ready', 'failed', 'deleted'))
);
--> statement-breakpoint
CREATE TABLE "chat_attachments" (
	"message_id" text NOT NULL,
	"asset_id" text NOT NULL,
	"kind" text NOT NULL,
	"target_layer_id" text,
	"position" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "chat_attachments_message_id_asset_id_pk" PRIMARY KEY("message_id","asset_id"),
	CONSTRAINT "chat_attachments_kind_check" CHECK ("chat_attachments"."kind" IN ('reference', 'mask'))
);
--> statement-breakpoint
CREATE TABLE "chat_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"thread_id" text NOT NULL,
	"owner_id" text NOT NULL,
	"role" text NOT NULL,
	"kind" text NOT NULL,
	"content" text NOT NULL,
	"target_layer_id" text,
	"base_revision_id" text,
	"image_placement" text DEFAULT 'replace' NOT NULL,
	"sequence" integer NOT NULL,
	"revision_id" text,
	"job_id" text,
	"status" text DEFAULT 'complete' NOT NULL,
	"plan_id" text,
	"plan_revision" integer,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "chat_messages_role_check" CHECK ("chat_messages"."role" IN ('user', 'assistant', 'system')),
	CONSTRAINT "chat_messages_kind_check" CHECK ("chat_messages"."kind" IN ('text', 'image', 'image_edit', 'animation', 'device_edit', 'plan', 'export', 'status')),
	CONSTRAINT "chat_messages_status_check" CHECK ("chat_messages"."status" IN ('complete', 'streaming', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "chat_threads" (
	"id" text PRIMARY KEY NOT NULL,
	"sticker_id" text NOT NULL,
	"owner_id" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "creator_profiles" (
	"user_id" text PRIMARY KEY NOT NULL,
	"handle" text NOT NULL,
	"display_name" text,
	"bio" text,
	"avatar_asset_id" text,
	"payout_status" text DEFAULT 'none' NOT NULL,
	"payout_provider" text,
	"payout_account_ref" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "creator_profiles_payout_status_check" CHECK ("creator_profiles"."payout_status" IN ('none', 'pending', 'active'))
);
--> statement-breakpoint
CREATE TABLE "device_tokens" (
	"token" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"platform" text DEFAULT 'ios' NOT NULL,
	"environment" text DEFAULT 'production' NOT NULL,
	"bundle_id" text,
	"app_version" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone NOT NULL,
	"disabled_at" timestamp with time zone,
	"disabled_reason" text,
	CONSTRAINT "device_tokens_platform_check" CHECK ("device_tokens"."platform" IN ('ios')),
	CONSTRAINT "device_tokens_environment_check" CHECK ("device_tokens"."environment" IN ('sandbox', 'production'))
);
--> statement-breakpoint
CREATE TABLE "generation_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "generation_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" text NOT NULL,
	"owner_id" text NOT NULL,
	"type" text NOT NULL,
	"data_json" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "generation_events_type_check" CHECK ("generation_events"."type" IN ('queued', 'started', 'progress', 'document', 'candidate', 'waiting', 'completed', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "generation_jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"sticker_id" text NOT NULL,
	"source_message_id" text,
	"kind" text NOT NULL,
	"quick" boolean DEFAULT false NOT NULL,
	"prior_sticker_status" text,
	"state" text DEFAULT 'queued' NOT NULL,
	"workflow_run_id" text,
	"reservation_id" text,
	"reservation_amount" integer DEFAULT 0 NOT NULL,
	"api_text_cost_nanodollars" bigint DEFAULT 0 NOT NULL,
	"api_image_cost_nanodollars" bigint DEFAULT 0 NOT NULL,
	"api_image_points" integer DEFAULT 0 NOT NULL,
	"api_video_cost_nanodollars" bigint DEFAULT 0 NOT NULL,
	"api_video_points" integer DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"error_code" text,
	"error_message" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	CONSTRAINT "generation_jobs_kind_check" CHECK ("generation_jobs"."kind" IN ('image', 'edit', 'animation', 'chat', 'plan', 'compose', 'export', 'cleanup')),
	CONSTRAINT "generation_jobs_state_check" CHECK ("generation_jobs"."state" IN ('queued', 'running', 'waiting', 'succeeded', 'failed', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"owner_id" text NOT NULL,
	"operation" text NOT NULL,
	"key" text NOT NULL,
	"request_hash" text NOT NULL,
	"response_status" integer,
	"response_json" jsonb,
	"created_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "idempotency_keys_owner_id_operation_key_pk" PRIMARY KEY("owner_id","operation","key")
);
--> statement-breakpoint
CREATE TABLE "pack_installs" (
	"pack_id" text NOT NULL,
	"user_id" text NOT NULL,
	"state" text DEFAULT 'installed' NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"acquisition" text DEFAULT 'free' NOT NULL,
	"price_cents_paid" integer DEFAULT 0 NOT NULL,
	"order_ref" text,
	"installed_at" timestamp with time zone NOT NULL,
	"uninstalled_at" timestamp with time zone,
	CONSTRAINT "pack_installs_pack_id_user_id_pk" PRIMARY KEY("pack_id","user_id"),
	CONSTRAINT "pack_installs_state_check" CHECK ("pack_installs"."state" IN ('installed', 'uninstalled')),
	CONSTRAINT "pack_installs_acquisition_check" CHECK ("pack_installs"."acquisition" IN ('free', 'purchase', 'gift', 'promo'))
);
--> statement-breakpoint
CREATE TABLE "plans" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"sticker_id" text NOT NULL,
	"thread_id" text NOT NULL,
	"message_id" text NOT NULL,
	"plan_json" jsonb NOT NULL,
	"state" text DEFAULT 'draft' NOT NULL,
	"revision" integer DEFAULT 1 NOT NULL,
	"supersedes_id" text,
	"job_id" text,
	"concept_asset_id" text,
	"decision_reason" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"decided_at" timestamp with time zone,
	CONSTRAINT "plans_state_check" CHECK ("plans"."state" IN ('draft', 'finalized', 'confirmed', 'superseded', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "sticker_pack_items" (
	"pack_id" text NOT NULL,
	"sticker_id" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"added_at" timestamp with time zone NOT NULL,
	CONSTRAINT "sticker_pack_items_pack_id_sticker_id_pk" PRIMARY KEY("pack_id","sticker_id")
);
--> statement-breakpoint
CREATE TABLE "sticker_packs" (
	"id" text PRIMARY KEY NOT NULL,
	"creator_id" text NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"summary" text,
	"state" text DEFAULT 'draft' NOT NULL,
	"cover_sticker_id" text,
	"item_count" integer DEFAULT 0 NOT NULL,
	"install_count" integer DEFAULT 0 NOT NULL,
	"install_total" integer DEFAULT 0 NOT NULL,
	"monetization" text DEFAULT 'free' NOT NULL,
	"price_cents" integer DEFAULT 0 NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"revenue_share_bps" integer DEFAULT 0 NOT NULL,
	"published_at" timestamp with time zone,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "sticker_packs_state_check" CHECK ("sticker_packs"."state" IN ('draft', 'published', 'unlisted', 'removed')),
	CONSTRAINT "sticker_packs_monetization_check" CHECK ("sticker_packs"."monetization" IN ('free', 'paid', 'subscription'))
);
--> statement-breakpoint
CREATE TABLE "sticker_revisions" (
	"id" text PRIMARY KEY NOT NULL,
	"sticker_id" text NOT NULL,
	"parent_revision_id" text,
	"source_message_id" text,
	"kind" text NOT NULL,
	"candidate_state" text DEFAULT 'candidate' NOT NULL,
	"document_json" jsonb NOT NULL,
	"master_asset_id" text,
	"preview_asset_id" text,
	"png_asset_id" text,
	"gif_asset_id" text,
	"apng_asset_id" text,
	"mp4_asset_id" text,
	"system_asset_id" text,
	"attachment_medium_asset_id" text,
	"attachment_small_asset_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"decided_at" timestamp with time zone,
	CONSTRAINT "sticker_revisions_kind_check" CHECK ("sticker_revisions"."kind" IN ('static', 'animated')),
	CONSTRAINT "sticker_revisions_candidate_state_check" CHECK ("sticker_revisions"."candidate_state" IN ('candidate', 'accepted', 'rejected', 'superseded'))
);
--> statement-breakpoint
CREATE TABLE "stickers" (
	"id" text PRIMARY KEY NOT NULL,
	"owner_id" text NOT NULL,
	"title" text NOT NULL,
	"kind" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"active_revision_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "stickers_kind_check" CHECK ("stickers"."kind" IN ('static', 'animated')),
	CONSTRAINT "stickers_status_check" CHECK ("stickers"."status" IN ('draft', 'published', 'deleting'))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text,
	"display_name" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_attachments" ADD CONSTRAINT "chat_attachments_message_id_chat_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."chat_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_attachments" ADD CONSTRAINT "chat_attachments_asset_id_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_thread_id_chat_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_job_id_generation_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."generation_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_messages" ADD CONSTRAINT "chat_messages_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_threads" ADD CONSTRAINT "chat_threads_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creator_profiles" ADD CONSTRAINT "creator_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creator_profiles" ADD CONSTRAINT "creator_profiles_avatar_asset_id_assets_id_fk" FOREIGN KEY ("avatar_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "device_tokens" ADD CONSTRAINT "device_tokens_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generation_events" ADD CONSTRAINT "generation_events_job_id_generation_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."generation_jobs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generation_events" ADD CONSTRAINT "generation_events_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_installs" ADD CONSTRAINT "pack_installs_pack_id_sticker_packs_id_fk" FOREIGN KEY ("pack_id") REFERENCES "public"."sticker_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pack_installs" ADD CONSTRAINT "pack_installs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_thread_id_chat_threads_id_fk" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_threads"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_message_id_chat_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."chat_messages"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_supersedes_id_plans_id_fk" FOREIGN KEY ("supersedes_id") REFERENCES "public"."plans"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_job_id_generation_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."generation_jobs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "plans" ADD CONSTRAINT "plans_concept_asset_id_assets_id_fk" FOREIGN KEY ("concept_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_pack_items" ADD CONSTRAINT "sticker_pack_items_pack_id_sticker_packs_id_fk" FOREIGN KEY ("pack_id") REFERENCES "public"."sticker_packs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_pack_items" ADD CONSTRAINT "sticker_pack_items_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_packs" ADD CONSTRAINT "sticker_packs_creator_id_users_id_fk" FOREIGN KEY ("creator_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_packs" ADD CONSTRAINT "sticker_packs_cover_sticker_id_stickers_id_fk" FOREIGN KEY ("cover_sticker_id") REFERENCES "public"."stickers"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_sticker_id_stickers_id_fk" FOREIGN KEY ("sticker_id") REFERENCES "public"."stickers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_source_message_id_chat_messages_id_fk" FOREIGN KEY ("source_message_id") REFERENCES "public"."chat_messages"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_master_asset_id_assets_id_fk" FOREIGN KEY ("master_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_preview_asset_id_assets_id_fk" FOREIGN KEY ("preview_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_png_asset_id_assets_id_fk" FOREIGN KEY ("png_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_gif_asset_id_assets_id_fk" FOREIGN KEY ("gif_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_apng_asset_id_assets_id_fk" FOREIGN KEY ("apng_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_mp4_asset_id_assets_id_fk" FOREIGN KEY ("mp4_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_system_asset_id_assets_id_fk" FOREIGN KEY ("system_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_attachment_medium_asset_id_assets_id_fk" FOREIGN KEY ("attachment_medium_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sticker_revisions" ADD CONSTRAINT "sticker_revisions_attachment_small_asset_id_assets_id_fk" FOREIGN KEY ("attachment_small_asset_id") REFERENCES "public"."assets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stickers" ADD CONSTRAINT "stickers_owner_id_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "assets_owner_created_idx" ON "assets" USING btree ("owner_id","created_at");--> statement-breakpoint
CREATE INDEX "assets_sticker_kind_idx" ON "assets" USING btree ("sticker_id","kind");--> statement-breakpoint
CREATE INDEX "chat_attachments_asset_idx" ON "chat_attachments" USING btree ("asset_id");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_messages_thread_sequence_unique" ON "chat_messages" USING btree ("thread_id","sequence");--> statement-breakpoint
CREATE INDEX "chat_messages_thread_created_idx" ON "chat_messages" USING btree ("thread_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "chat_threads_sticker_unique" ON "chat_threads" USING btree ("sticker_id");--> statement-breakpoint
CREATE INDEX "chat_threads_owner_idx" ON "chat_threads" USING btree ("owner_id");--> statement-breakpoint
CREATE UNIQUE INDEX "creator_profiles_handle_unique" ON "creator_profiles" USING btree ("handle");--> statement-breakpoint
CREATE INDEX "device_tokens_user_active_idx" ON "device_tokens" USING btree ("user_id","disabled_at");--> statement-breakpoint
CREATE INDEX "generation_events_job_id_idx" ON "generation_events" USING btree ("job_id","id");--> statement-breakpoint
CREATE INDEX "generation_events_owner_id_idx" ON "generation_events" USING btree ("owner_id","id");--> statement-breakpoint
CREATE INDEX "generation_jobs_owner_created_idx" ON "generation_jobs" USING btree ("owner_id","created_at");--> statement-breakpoint
CREATE INDEX "generation_jobs_sticker_state_idx" ON "generation_jobs" USING btree ("sticker_id","state");--> statement-breakpoint
CREATE UNIQUE INDEX "generation_jobs_one_active_per_sticker" ON "generation_jobs" USING btree ("sticker_id") WHERE "generation_jobs"."state" IN ('queued', 'running', 'waiting');--> statement-breakpoint
CREATE INDEX "idempotency_keys_expiry_idx" ON "idempotency_keys" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "pack_installs_user_state_idx" ON "pack_installs" USING btree ("user_id","state","position","installed_at","pack_id");--> statement-breakpoint
CREATE INDEX "pack_installs_pack_state_idx" ON "pack_installs" USING btree ("pack_id","state");--> statement-breakpoint
CREATE INDEX "plans_sticker_state_idx" ON "plans" USING btree ("sticker_id","state");--> statement-breakpoint
CREATE INDEX "plans_owner_created_idx" ON "plans" USING btree ("owner_id","created_at");--> statement-breakpoint
CREATE INDEX "sticker_pack_items_pack_position_idx" ON "sticker_pack_items" USING btree ("pack_id","position","sticker_id");--> statement-breakpoint
CREATE INDEX "sticker_pack_items_sticker_idx" ON "sticker_pack_items" USING btree ("sticker_id");--> statement-breakpoint
CREATE UNIQUE INDEX "sticker_packs_slug_unique" ON "sticker_packs" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "sticker_packs_creator_updated_idx" ON "sticker_packs" USING btree ("creator_id","updated_at");--> statement-breakpoint
CREATE INDEX "sticker_packs_state_published_idx" ON "sticker_packs" USING btree ("state","published_at");--> statement-breakpoint
CREATE INDEX "sticker_packs_state_installs_idx" ON "sticker_packs" USING btree ("state","install_count");--> statement-breakpoint
CREATE INDEX "sticker_revisions_sticker_created_idx" ON "sticker_revisions" USING btree ("sticker_id","created_at");--> statement-breakpoint
CREATE INDEX "sticker_revisions_parent_idx" ON "sticker_revisions" USING btree ("parent_revision_id");--> statement-breakpoint
CREATE INDEX "stickers_owner_updated_idx" ON "stickers" USING btree ("owner_id","updated_at","id");--> statement-breakpoint
CREATE INDEX "stickers_owner_status_updated_idx" ON "stickers" USING btree ("owner_id","status","updated_at","id");