import type { ComponentType } from "react";
export const tutorialContent: Record<string, () => Promise<{ default: ComponentType }>> = {
  "en/static": () => import("@/content/tutorial/en/static.mdx"),
  "en/animated": () => import("@/content/tutorial/en/animated.mdx"),
  "en/controllable": () => import("@/content/tutorial/en/controllable.mdx"),
  "en/finish": () => import("@/content/tutorial/en/finish.mdx"),
  "en/packs": () => import("@/content/tutorial/en/packs.mdx"),
  "en/new-pack": () => import("@/content/tutorial/en/new-pack.mdx"),
  "en/whatsapp": () => import("@/content/tutorial/en/whatsapp.mdx"),
  "en/telegram": () => import("@/content/tutorial/en/telegram.mdx"),
  "zh-CN/static": () => import("@/content/tutorial/zh-CN/static.mdx"),
  "zh-CN/animated": () => import("@/content/tutorial/zh-CN/animated.mdx"),
  "zh-CN/controllable": () => import("@/content/tutorial/zh-CN/controllable.mdx"),
  "zh-CN/finish": () => import("@/content/tutorial/zh-CN/finish.mdx"),
  "zh-CN/packs": () => import("@/content/tutorial/zh-CN/packs.mdx"),
  "zh-CN/new-pack": () => import("@/content/tutorial/zh-CN/new-pack.mdx"),
  "zh-CN/whatsapp": () => import("@/content/tutorial/zh-CN/whatsapp.mdx"),
  "zh-CN/telegram": () => import("@/content/tutorial/zh-CN/telegram.mdx"),
  "zh-HK/static": () => import("@/content/tutorial/zh-HK/static.mdx"),
  "zh-HK/animated": () => import("@/content/tutorial/zh-HK/animated.mdx"),
  "zh-HK/controllable": () => import("@/content/tutorial/zh-HK/controllable.mdx"),
  "zh-HK/finish": () => import("@/content/tutorial/zh-HK/finish.mdx"),
  "zh-HK/packs": () => import("@/content/tutorial/zh-HK/packs.mdx"),
  "zh-HK/new-pack": () => import("@/content/tutorial/zh-HK/new-pack.mdx"),
  "zh-HK/whatsapp": () => import("@/content/tutorial/zh-HK/whatsapp.mdx"),
  "zh-HK/telegram": () => import("@/content/tutorial/zh-HK/telegram.mdx"),
};
