import type { TutorialLocale } from "./catalog";
export const strings = {
  "en": {
    "title": "Tutorials",
    "intro": "A little guidance. A lot of sticker magic.",
    "create": "Create stickers",
    "finish": "Finish your sticker",
    "packs": "Sticker packs",
    "next": "Next",
    "scrollDown": "Scroll down",
    "back": "Back",
    "done": "Finish chapter",
    "index": "All chapters",
    "resume": "Continue reading",
    "tryIt": "Try it in the app",
    "completed": "Completed",
    "step": "Step",
    "of": "of",
    "play": "Play demonstration",
    "pause": "Pause demonstration",
    "restart": "Read again",
    "nextChapter": "Next chapter",
    "mediaError": "This image could not load. Try again when you are online.",
    "retry": "Retry",
    "language": "Language",
    "tip": "A little tip",
    "appHint": "Opens Winky Sticker Factory. It will not generate or send anything.",
    "read": "Read chapter"
  },
  "zh-CN": {
    "title": "教程",
    "intro": "一点指引，开启贴纸创作。",
    "create": "创建贴纸",
    "finish": "完成你的贴纸",
    "packs": "贴纸包",
    "next": "下一步",
    "scrollDown": "向下滚动",
    "back": "上一步",
    "done": "完成章节",
    "index": "全部章节",
    "resume": "继续阅读",
    "tryIt": "在应用中试试",
    "completed": "已完成",
    "step": "步骤",
    "of": "/",
    "play": "播放演示",
    "pause": "暂停演示",
    "restart": "重新阅读",
    "nextChapter": "下一章节",
    "mediaError": "图片加载失败。联网后请重试。",
    "retry": "重试",
    "language": "语言",
    "tip": "小提示",
    "appHint": "打开 Winky Sticker Factory，不会自动生成或发送。",
    "read": "阅读章节"
  },
  "zh-HK": {
    "title": "教學",
    "intro": "一點指引，開啟貼紙創作。",
    "create": "建立貼紙",
    "finish": "完成你的貼紙",
    "packs": "貼紙包",
    "next": "下一步",
    "scrollDown": "向下捲動",
    "back": "上一步",
    "done": "完成章節",
    "index": "全部章節",
    "resume": "繼續閱讀",
    "tryIt": "在應用程式中試試",
    "completed": "已完成",
    "step": "步驟",
    "of": "/",
    "play": "播放示範",
    "pause": "暫停示範",
    "restart": "重新閱讀",
    "nextChapter": "下一章節",
    "mediaError": "圖片載入失敗。連線後請重試。",
    "retry": "重試",
    "language": "語言",
    "tip": "小提示",
    "appHint": "打開 Winky Sticker Factory，不會自動產生或傳送。",
    "read": "閱讀章節"
  }
} satisfies Record<TutorialLocale, Record<string, string>>;
